[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://ad-viewer-api.netlify.app"

[[redirects]]
  from = "/api/*"
  to = "https://ad-viewer-api.netlify.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200